### PR TITLE
Patch palette into GIF file.

### PR DESCRIPTION
**Pull request by rdebath**
The Linux console has the ability to configure the 24bit colours mapped to the 16 selected colours.
These patches allow you to choose the colours to be used in the gif file BUT only if they are configured during the characters selected by the time entries containing the first 60 milliseconds of the script.

To do this you would need to be something like this line in the `.bashrc` file or as an initial command on the `-c` option of script:
```
echo -ne '\E]P0073642\E\\\E]P1dc322f\E\\\E]P2329900\E\\\E]P3b58900\E\\\E]P4265ed2\E\\\E]P5d33682\E\\\E]P6269682\E\\\E]P793a1a1\E\\\E]P834636f\E\\\E]P9ff5f5c\E\\\E]Pa5fe22d\E\\\E]Pbe2b62d\E\\\E]Pc268bff\E\\\E]Pdff63af\E\\\E]Pe53c3af\E\\\E]Pfc0cece\E\\'
```

Later reconfigurations can probably be supported by generating local colour lookup tables in the GIF file but this patch does not do that. Full truecolor is potentially possible by abusing these local CLUTs, but IMO it's likely to trigger display bugs and is probably not required.

### CODE REVIEW

**Comment by lecram** [comment]
Fully supporting `ESC ] P` requires local color tables, which I don't want to use since they add complexity and generate bigger GIF files (*) for little benefit.
If we just want to configure the global color table -- without the need to edit `default.h` and recompile congif -- then my suggestion is adding a command-line option to specify a palette file in some basic format.

(*) not only because the color tables themselves must be stored uncompressed, but also because the frame size optimization used by our encoder would have to be disabled since it assumes the color table for the current frame is the same as the previous.

**Comment by rdebath** [comment]
Okay, I'll revisit this.

I think that you're not quite right about the local palette issue, while it would be necessary to add them if video palettes **are used**. It would have no impact on the GIF when OSC-P is unused. Further if they are used doing some complex attempt at optimisation wouldn't get anywhere near a quick post-processing with `gifsicle -b -O3 file.gif`.

Your command line suggestion is well taken, even if local palettes could be used it would be best if there were a well defined target for OSC-R.

**Comment by rdebath** [comment]
Here's the revamp...

The Linux kernel works in three different modes depending on if the screen is TextMode, 256 colour or 16M colour. The 16M mode is especially glitchy!
I am assuming that we're emulating the 256 colour mode this means that there is **no blinking** and the palette changes across the whole image as soon as it is requested. With this model there is little cost in complexity and no cost in the GIF size if `OSC P` isn't used.

This patch sets the global palette from the palette defined by the `-p` option, this can be one of a small set of predefined settings (eg: @vga, @xterm, @solarized etc) or a file containing lines of the form `colour0 = #000000`. If the script doesn't change the video palette the global GIF palette is sufficient and everything works as before.

Only when the script makes a palette change does the updated routine create a local palette. This palette applies to all frames after setting the palette to something different. If you reset the palette with `OSC R` or only make changes that don't change the colours it will continue to use the global palette. Furthermore the bounding box updates will continue to work _between frames where the palette does not change_ only triggering a full redraw when the video palette is marked as "dirty".

This gives the same compression when not using local palettes, but still supports the more complex usage. It does **not** add complexity to increase the size of the global GIF palette or add transparent pixels or any other possible "optimisations". Frankly, as I said before, I would recommend using `gifsicle -b -O3 file.gif` for really complex playbacks as that command can already shrink the size (sometimes quite a bit) because it knows about transparent pixels.

BTW: Most of the patch is reading the text colour map and the predefined palettes.

**Comment by lecram** [comment]
Great work! Thanks!

**Pull request merged**
